packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'example'
  - 'storybook'
  - 'examples'
  - 'docs'
  # exclude packages that are inside test directories
  - '!**/test/**'